baseURL = 'https://blog.rduffy.uk/'
languageCode = 'en-gb'
title = 'Ryan Duffy - AI Infrastructure & Local LLM Journey'
theme = 'PaperMod'

[params]
  description = "Technical deep-dives into AI infrastructure, local LLM performance tuning, and automation engineering"
  author = "Ryan Duffy"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

[params.homeInfoParams]
  Title = "Hi, I'm Ryan 👋"
  Content = """
  I'm documenting my journey building a local AI infrastructure stack on consumer hardware.

  **What you'll find here:**
  - RTX 4080 LLM performance tuning
  - vLLM, Ollama, and inference optimization
  - Kubernetes observability (Jaeger, OpenTelemetry, Kafka)
  - Obsidian vault automation with ChromaDB
  - Real-world benchmarks and learnings
  """

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/rduffyuk"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
